### PR TITLE
Handle local policy

### PR DESCRIPTION
**Pull request by clyang82**
Do not handle the policy which has `hub-of-hubs.open-cluster-management.io/local-policy` annotation. it will be handled by policy-propogator as a local policy.

### CODE REVIEW

**Review by nirrozenbaum — COMMENTED** [review]
@clyang82 
I understand the motivation of why we need logic to determine if we need to process the CR or not.
this is not the k8s way for filtering out CRs based on some criteria.
(it's true that HoH is not fully k8s native, but we do keep the k8s style whenever that's possible and intuitive).

in this case, hub of hubs spec sync has k8s native controllers.
the k8s way for filtering watch events is using predicates.
see for example here:
https://github.com/stolostron/hub-of-hubs-spec-sync/blob/main/pkg/controller/subscription_spec_sync.go#L17-L19
or here:
https://github.com/stolostron/hub-of-hubs-spec-sync/blob/main/pkg/controller/hoh_config_spec_sync.go#L24-L26

in our case, I think we should remove the "processInstance" function and just provide a simple predicate in the initialization of the controllers as we did in the above examples.
this is a generalized approach where you can add conditions for getting watch events on CRs and decide which CRs you want to filter out from your controller.

**Comment by nirrozenbaum** [comment]
btw, do you think we can call it with a name other than `local-policy`? 
that was a bit confusing since we refer to policies that are created locally in LHs as local policies.
maybe `leaf-hub-policy`? or `hub-policy`?

**Comment by clyang82** [comment]
Thanks @nirrozenbaum for your comments. I have changed to use `predicate` for watching events. I would like to continue to use `local-policy`. if needed, we can set the different values to distinguish where is the policy from.

**Review by nirrozenbaum — COMMENTED** [review]
@clyang82 thanks for the changes.
I think it looks much better.
a few comments on current code:

1. rootPolicy labels is not used. looks like a bug.
2. a question - do you add the annotation `local-policy` on placementrule and placementbinding as well? I assume you do, it makes sense. asking just to make sure.
3. we just finished a discussion with the team at Haifa regarding other topics (subscriptions, Gitops), and we understood that in other cases it's useful to mark the resource as a `local-resource` that we shouldn't propagate to LHs. when we talked about it in our meeting, I thought about your implementation in this PR.
do you think we can generalize your idea and call the annotation `local-resource` and then reuse it in other places?

let me know what do you think and then we can merge it.

**Comment by clyang82** [comment]
Thanks @nirrozenbaum 
1. Yes. it was used in the past. Good catch, let me remove it.
2. Yes. I add this annotation for placementrule/placementbinding/policy 
3. I like the idea to generalize it and call `local-resource`. Do you expect me to update it in this PR as well?

**Comment by nirrozenbaum** [comment]
> 3. I like the idea to generalize it and call `local-resource`. Do you expect me to update it in this PR as well?

@clyang82 if this is not a big overhead for you, then it will be helpful.
I assume it should be easy just to change the annotation name (anyway we need to push another commit to remove the label that is not used).
if that's an overhead, we can then merge the PR and I'll change the annotation name later.

**Comment by clyang82** [comment]
I need to change the annotation name in policy ui as well. let me update it here firstly.

**Review by nirrozenbaum — APPROVED** [review]
/lgtm

**Pull request merged**
